apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: "2023-03-01T10:40:35Z"
  labels:
    app: webapp
  name: webapp-svc
  namespace: default
  resourceVersion: "1129189"
  uid: 79d300e8-7b61-4270-9431-0e00fde6cc6e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.82.165
  clusterIPs:
  - 10.98.82.165
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32175
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.56.249
