apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  type: LoadBalancer
