apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx
        name: nginx
        
